name: Deploy to Droplet

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Deploy to Droplet
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@206.189.138.180 << 'EOF'
          echo "Updating config.json with database credentials..."
          cat > /root/automation/config.json << CONFIG
          {
            "host": "${{ secrets.DB_HOST }}",
            "user": "${{ secrets.DB_USER }}",
            "password": "${{ secrets.DB_PASSWORD }}"
          }
CONFIG
          cd /root/automation
          git pull origin main
          # Restart your app or perform other necessary steps
          # Example: systemctl restart your-app
        EOF

# Notes:
# 1. Replace `DB_HOST`, `DB_USER`, and `DB_PASSWORD` with your GitHub Secrets names.
# 2. Ensure `config.json` is not accidentally overwritten elsewhere or added to `.gitignore`.
# 3. If you need additional database configuration fields, they can be added similarly in the `cat` block.
