name: Deploy to Droplet

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install jq and sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass jq

    - name: Deploy to Droplet
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@206.189.138.180 << 'EOF'
          # Update only the database credentials directly in config.json
          jq '.frameworkdatabase.host="${{ secrets.DB_HOST }}" |
              .frameworkdatabase.user="${{ secrets.DB_USER }}" |
              .frameworkdatabase.password="${{ secrets.DB_PASSWORD }}" |
              .moduledatabase.host="${{ secrets.DB_HOST }}" |
              .moduledatabase.user="${{ secrets.DB_USER }}" |
              .moduledatabase.password="${{ secrets.DB_PASSWORD }}" |
              .adminmoduledatabase.host="${{ secrets.DB_HOST }}" |
              .adminmoduledatabase.user="${{ secrets.DB_USER }}" |
              .adminmoduledatabase.password="${{ secrets.DB_PASSWORD }}"' \
              /root/automation/config.json > /root/automation/config.json

          # Ensure the application uses the updated config
          cd /root/automation
          git pull origin main
          # Restart your app or perform other necessary steps
          # Example: systemctl restart your-app
        EOF
